### PR TITLE
Include demonyms

### PR DESCRIPTION
**Pull request by Gilstroem**
Including demonyms will allow flags to be matched against strings such as 'Danish man', et cetera. I can not see any immediate downsides, apart perhaps from performance, which should not be impacted too much.

I think it would expand the use cases for this great little library 🎉

The demonyms are derived from this repo: https://github.com/mledoze/countries/blob/master/countries.json

### CODE REVIEW

**Comment by meeDamian** [comment]
Hey @Gilstroem, I'm happy to add it, just please add some tests to make sure correct code/name/flag is returned given a few demonyms, and format JSON with standard spaces after colons and commas.

**Comment by marcusique** [comment]
Would be great to have this feature! Are you planning on merging this?

**Comment by Gilstroem** [comment]
Sorry - I've just gotten my laptop back from repair. @marcusique  I've fixed the JSON issues, and am in the process of adding a few tests, after which it will hopefully be merged 😊

**Comment by meeDamian** [comment]
I would definitely like to merge this in, although there's one issue.  This change introduces the possibility of multiple _correct_ outputs for the same exact-match output.

Example:

What would be the correct return for: `code('Dominican')`?  And why 🙂?

**Comment by meeDamian** [comment]
I've added a relevant test here: e63299c76f8f55a0f3f762c7590835ae966d8920, and while it passes on `master`, it unfortunately fails when run against this PR with:

```
10 non-unique values present:
  	5 occurences of French
  	3 occurences of American
  	2 occurences of Congolese
  	2 occurences of Djibouti
  	2 occurences of Dominican
  	2 occurences of Channel Islander
  	2 occurences of Gibraltar
  	2 occurences of Indian
  	2 occurences of Norwegian
  	2 occurences of Virgin Islander

```

I'm open to suggestions.

**Comment by marcusique** [comment]
> My guess would be that, since these can only be the input, leaving just one of each occurrences that matches best, would be the most optimal way forward, but I'm open to any suggestions.

Sounds like it would be the best possible solution. Something like:
Germany -> 🇩🇪
German -> 🇩🇪
Germa -> ❌
Germani -> ❌

Especially when it comes to something like:
The Netherlands -> 🇳🇱
Dutch -> 🇳🇱

**Comment by Gilstroem** [comment]
@meeDamian, thanks for adding the tests - I ran into the same issues, and did not have time at the time to think thoroughly about it. 

The only solution I've come up with is returning multiple ranked matches when multiple occurrences happen, but that would definitely be against the simplicity of the library - closest or no match as @marcusique suggests is probably the solution most in-line with the spirit of the library.

**Comment by meeDamian** [comment]
I think so too.  Happy to merge it in once there's no more conflicts :).

**Comment by meeDamian** [comment]
Hey @Gilstroem are you going to fix the mapping?

**Comment by Gilstroem** [comment]
@meeDamian sorry I did not have time to get back to you before now. I'm afraid I will not have time to make the final changes for the foreseeable future as I'm sitting with some big projects right now. 

Once again, sorry, I hope this will resolve somehow, I'm still a huge fan of the library, so thanks for providing it 🙏🏼

**Comment by meeDamian** [comment]
> @meeDamian sorry I did not have time to get back to you before now. I'm afraid I will not have time to make the final changes for the foreseeable future as I'm sitting with some big projects right now.
> 
> Once again, sorry, I hope this will resolve somehow, I'm still a huge fan of the library, so thanks for providing it 🙏🏼

No worries at all.  Do you mind if I finish, and merge it?

**Comment by Gilstroem** [comment]
Not at all - that'd be great

**Comment by meeDamian** [comment]
Deployed as [`v1.5.0`](https://travis-ci.org/meeDamian/country-emoji/jobs/586689974).

**Pull request merged**
