### PR TITLE
Added square brackets where its missing

### PR DESCRIPTION
**Pull request by Phumix**

### CODE REVIEW

**Comment by meeDamian** [comment]
They're not missing, why add them?

**Comment by Phumix** [comment]
They are indeed missing. But they are not needed.
________________________________

**Comment by BrodaNoel** [comment]
Missing in the current code, but present in the branch `1.6`

**Comment by BrodaNoel** [comment]
We just fixed this in https://github.com/meeDamian/country-emoji/pull/47
Adding the square brackets was not enough. We also had to change some small things in the code (removing some `Array.isArray` validations)

**Pull request closed without merging**
